- admin-frontend/src/App.js
- admin-frontend/src/components/junior.js
- admin-frontend/src/providers/dataProvider.js
- admin-frontend/src/providers/juniorProvider.js
> Add junior creation

- backend/src/club/club.controller.ts
- backend/src/club/club.service.spec.ts
- backend/src/club/club.service.ts
- backend/src/club/entities/checkin.entity.ts
- backend/src/club/vm/index.ts
- backend/src/club/vm/logbookCheckIns.vm.ts
Allows a list of all juniors who have check-in to be provided.
> Logbook checkin list api

- admin-frontend/src/api.js
- admin-frontend/src/components/logbook.js
- admin-frontend/src/components/logbookList.js
- admin-frontend/src/components/styledComponents/logbook.js
- admin-frontend/src/components/youthClub.js
- admin-frontend/src/customRoutes.js
- backend/src/club/club.controller.ts
- backend/src/club/club.service.spec.ts
- backend/src/club/club.service.ts
- backend/src/club/entities/checkin.entity.ts
- backend/src/club/vm/index.ts
- backend/src/club/vm/logbookCheckIns.vm.ts
Please review https://github.com/City-of-Vantaa-SmartLab/Mobiilinutakortti/pull/44 first
Provides UI for the check-ins logbook lists
> Logbook checkin list admin

- admin-frontend/src/components/junior.js
- frontend/src/components/RegistrationView/Form.tsx
frontend status fixed +delete 'required' from kuvauslupa
> minor fixes

- admin-frontend/src/App.js
- admin-frontend/src/components/checkIn/checkIn.js
- admin-frontend/src/components/youthClub.js
- backend/src/club/club.controller.ts
- backend/src/utils/helpers.ts
Bit odd PR. It also includes a duplicate-checkin fix, that I noticed while making this PR. Since it was oneliner, and a critical one. I included it here.
> Qr reader auth removal

- admin-frontend/src/components/junior.js
- backend/src/junior/junior.service.ts
- frontend/package-lock.json
- frontend/src/apis/index.ts
- frontend/src/components/QR/QR.tsx
- frontend/src/components/QRPage/QRPage.tsx
-Fixes errors with repetitive status changing (active challenge is now checked and removed every time before creating a new one)
-Warning message is added in admin frontend when status of the application is changed from pending to accepted. Warning is also displayed when junior is created in admin panel and status 'accepted' is chosen
> Status bug

- admin-frontend/src/App.js
- admin-frontend/src/components/junior.js
- admin-frontend/src/components/youthClub.js
- admin-frontend/src/components/youthWorker.js
- admin-frontend/src/utils.js
- frontend/src/components/QRPage/QRPage.tsx
> fix texts: talo -> tila + some others

- admin-frontend/src/components/youthWorker.js
> fix: show names, not id numbers in admin view

- frontend/src/actions/authActions.ts
- frontend/src/components/ParentRegistration/RegistrationView/Form.tsx
- frontend/src/components/ParentRegistration/StyledComponents.tsx
- frontend/src/components/loginPage/loginPage.tsx
- frontend/src/reducers/authReducer.ts
- frontend/src/types/authTypes.ts
- frontend/src/utils/index.tsx
includes the previous PR changes
> remove button disabling and add notification to terms of use checkbox

- README.md
- backend/README.md
- backend/src/junior/junior.controller.ts
- backend/src/junior/junior.service.ts
> feat: add test data endpoints

- admin-frontend/src/api.js
- admin-frontend/src/providers/juniorProvider.js
- backend/src/common/vm/index.ts
- backend/src/common/vm/total.vm.ts
- backend/src/junior/junior.controller.ts
- backend/src/junior/junior.service.ts
- backend/src/junior/vm/index.ts
- backend/src/junior/vm/juniorList.vm.ts
- Include filtering by name in the query (search by full name)
- Fix pagination to display the real count of results after filtering is applied
> Fix junior filtering 

- backend/src/junior/pipes/phoneNumberValidation.pipe.ts
- frontend/src/components/ParentRegistration/RegistrationView/Form.tsx
MOI numbers can have one additional digit, and they are currently failing validation
> Update length range for phone number validation

- frontend/src/utils/index.tsx
Found one more phone validator
> Fix phone length range in link request form

- backend/package-lock.json
- backend/package.json
- frontend/src/components/ParentRegistration/RegistrationView/Form.tsx
- frontend/src/components/ParentRegistration/RegistrationView/index.tsx
- frontend/src/components/ParentRegistration/StyledComponents.tsx
-Add an attribute to the form to stop browsers from autofilling the fields
-Add a link to go back to the form after the application submission to make application for a second child easier
> Switch off form autocomplete / link to return to the form on submission

- backend/src/junior/junior.decorator.ts
The createParamDecorator API was changed in Nest 7.
> fix: fix Junior decorator

- README.md
- admin-frontend/README.md
- admin-frontend/task-definition.json
- backend/README.md
- backend/src/sso/sso.service.ts
- backend/task-definition.json
- frontend/README.md
- frontend/task-definition.json
The previously used mobiilinuta-admin-test.com is no longer available.
> fix: use load balancer url for api

- backend/src/content.json
- backend/src/junior/junior.service.ts
I try to look through all the logic both front and back to see if it work properly or not. But I still might miss something. Please run it on your machine and test the logic out again. Thank you!
> add logic to check for renew user

- admin-frontend/src/components/junior.js
The new statuses aren't all related to home calls, so a more generic
word is more suitable choice.
> feat: rename Kotisoitto ("Home call") field to Tila ("Status")

- admin-frontend/src/api.js
- admin-frontend/src/components/deleteExpiredUsers.js
- admin-frontend/src/components/newSeason.js
- admin-frontend/src/customRoutes.js
- admin-frontend/src/menu.js
- admin-frontend/src/state.js
Target branch will be changed to master once it has been merged. Review and merge new-season-button branch first.
> Delete expired users

- frontend/src/components/ParentRegistration/MainView/index.tsx
Add a mention about renewing the youth club card every season. Also add
line breaks to the paragraph to improve readability.
> feat: amend application form description text

- backend/src/content.json
- backend/src/junior/junior.service.ts
Creating a new season and deleting expired users will now return a
message in Finnish.
> feat: translate backend response messages

- README.md
- admin-frontend/README.md
- admin-frontend/task-definition.json
- backend/README.md
- backend/src/sso/sso.service.ts
- backend/task-definition.json
- frontend/README.md
- frontend/task-definition.json
This reverts commit 5bb46bfe8faa78f21f644b5766f4d6fc41f4d97a.
> Revert "fix: use load balancer url for api"

- admin-frontend/src/components/junior.js
- admin-frontend/src/providers/juniorProvider.js
- backend/src/junior/junior.service.ts
Add filter for the youth's phone number. Set auto focus for all text
input fields. Increase search debounce to 1000 ms.
> feat: improve youth list filters

- README.md
- admin-frontend/README.md
- docker-compose.yml
Port 5000 is reserved by some system service on macOS
> Move admin-frontend to port 3002

- admin-frontend/src/components/junior.js
- backend/src/junior/junior.service.ts
> feat: allow QR login link SMS sending in junior expired status

- admin-frontend/src/App.js
source: https://marmelab.com/react-admin/Admin.html
> feat: disable React Admin telemetry

- admin-frontend/src/components/junior.js
- backend/src/content.ts
- backend/src/junior/dto/register.dto.ts
- backend/src/junior/junior.service.ts
- Add communications language to junior creation form (it was only in the edit form)
- Support hidden junior fields in backend, too
> Fix creating junior from admin

- admin-frontend/src/components/extraEntry/extraEntry.js
- admin-frontend/src/components/styledComponents/extraEntry.js
- admin-frontend/src/providers/extraEntryProvider.js
- backend/src/extraEntry/extraEntry.controller.ts
- backend/src/extraEntry/extraEntry.service.ts
- backend/src/extraEntry/vm/juniorExtraEntries.vm.ts
> feat 3.2 task 8: Minor fixes to extra entry functionalities

- admin-frontend/src/components/junior.js
- backend/src/junior/dto/register.dto.ts
- backend/src/junior/interceptors/edit.interceptor.ts
- backend/src/utils/helpers.ts
> feat 3.2 task 9: Removed required from homeYouthClub and added dummy number to parent

- admin-frontend/src/App.js
- admin-frontend/src/components/entraLandingPage.js
Add login page for Entra Id authentication
> feat: 2023Q4/4: Add login page for Entra Id authentication
